---
-  name : Basic System Set up
   hosts : web
   become: true
   tasks:
    -   name : update all security-related pacakages
        ansible.builtin.pacakages:
            name : 'a'
            states : lastest
            security : true
    -   name : Create a new username
        ansible.builtin.users:
            name : roger
            states : present
            create_home : true
